// <auto-generated />
namespace App_Site_Touristique.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class migTest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migTest));
        
        string IMigrationMetadata.Id
        {
            get { return "202105152214399_migTest"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
